services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=fleetks-game
      - POSTGRES_PASSWORD=fleetks-gamepw
      - POSTGRES_DB=game-fleetks-game
    ports:
      - 127.0.0.1:5444:5432

  redis:
    image: redis:7.4
    ports:
      - 127.0.0.1:6379:6379